<?php

namespace AppBundle\Repositories;

use Doctrine\ORM\EntityRepository;

/**
 * GenRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenRegionRepository extends EntityRepository
{



public function listaProductos($valor)
{

//echo'<pre>';var_dump($valor);exit;
 $query = "
    SELECT
    a.id as id, 
    a.titulo as titulo,
    a.descripcion as descripcion,
    a.fechaInicio as fechaInicio,
    a.fechaTermino as fechaTermino,
    a.precio as precio,
    a.imagen as imagen,
    a.vendidos as vendidos,
    a.tags as tags
    FROM AppBundle\Entity\Producto a
    where a.titulo like :valor OR a.descripcion like :valor
    ";

    $query = $this->_em->createQuery($query);
    
    if($valor != null){
    $query->setParameter('valor','%'.$valor.'%');
    }

   // echo'<pre>';var_dump($query->getArrayResult());exit;
    // return $query->getArrayResult();
    return $query->getArrayResult();
    //return $query->getArrayResult(); 

}



public function listaProductosVendidos()
{

//echo'<pre>';var_dump($valor);exit;
    $query = "
    SELECT
    a.id as id, 
    a.titulo as titulo,
    a.descripcion as descripcion,
    a.fechaInicio as fechaInicio,
    a.fechaTermino as fechaTermino,
    a.precio as precio,
    a.imagen as imagen,
    a.vendidos as vendidos,
    a.tags as tags
    FROM AppBundle\Entity\Producto a
    order by a.vendidos DESC 
    ";

    $query = $this->_em->createQuery($query)->setMaxResults(20);


/*return $this->getEntityManager()
        ->createQuery('...')
        ->setMaxResults(5)
        ->setFirstResult(10)
        ->getResult(); */   

   // echo'<pre>';var_dump($query->getArrayResult());exit;
    // return $query->getArrayResult();

    return $query->getArrayResult();
    //return $query->getArrayResult(); 

}





}
